class MainPageLocators:
    how_much = ".//div[contains(text(), 'Сколько это стоит?')]"
    how_much_open = './/p[contains(text(), "Сутки — 400 рублей.")]/parent::div'
    want_more_bikes = './/div[contains(text(), "Хочу сразу несколько самокатов!")]'
    want_more_bikes_open = './/p[contains(text(), "Пока что у нас так: один заказ — один самокат")]/parent::div'
    how_count_time = './/div[contains(text(), "Как рассчитывается время")]'
    how_count_time_open = './/p[contains(text(), "Допустим, вы оформляете заказ на 8 мая.")]'
    can_order_now = './/div[contains(text(), "Можно ли заказать самокат прямо")]'
    can_order_now_open = './/p[contains(text(), "Только начиная с завтрашнего дня.")]/parent::div'
    can_prolong_order = './/div[contains(text(), "Можно ли продлить заказ")]'
    can_prolong_order_open = './/p[contains(text(), "Пока что нет!")]/parent::div'
    charge_station = './/div[contains(text(), "Вы привозите зарядку вместе")]'
    charge_station_open = './/p[contains(text(), "Самокат приезжает к вам с полной зарядкой.")]/parent::div'
    cancel_order = './/div[contains(text(), "Можно ли отменить")]'
    cancel_order_open = './/p[contains(text(), "Да, пока самокат не привезли.")]/parent::div'
    live_behind_mkad = './/div[contains(text(), "Я жизу за МКАДом")]'
    live_behind_mkad_open = './/p[contains(text(), "Да, обязательно.")]/parent::div'
    logo_ya = './/img[@alt="Yandex"]/parent::a'
    logo_samokat = './/img[@alt="Scooter"]/parent::a'
    order_header_btn = './/div[contains(@class,"Header_Nav__AGCXC")]//button[text() = "Заказать"]'
    order_middle_btn = './/div[contains(@class,"Home_FinishButton__1_cWm"]//button[text() = "Заказать"]'
    for_who_title = './/div[contains(@class,"Order_Content__bmtHS"]//div[text() = "Для кого самокат"]'
