class OrderPageLocators:
    for_who_title = './/div[@class="Order_Content__bmtHS"]//div[text() = "Для кого самокат"]'
    name_field = './/input[@placeholder="* Имя"]'
    last_name_field = './/input[@placeholder="* Фамилия"]'
    address_field = './/input[@placeholder="* Адрес: куда привезти заказ"]'
    metro_station_field = './/input[@placeholder="* Станция метро"]'
    metro_first = 'select-search__row'
    phone_field = './/input[@placeholder="* Телефон: на него позвонит курьер"]'
    next_btn = './/button[text()="Далее"]'
    about_rent_title = './/div[text()="Про аренду"]'
    when_bring_field = './/input[@placeholder="* Когда привезти самокат"]'
    rent_time_field = './/div[@class = "Dropdown-control"]'
    rent_time_field_1_day = './/div[contains(@class, "Dropdown-option") and contains(text(), "сутки")]'
    rent_time_field_2_days = './/div[contains(@class, "Dropdown-option") and contains(text(), "двое суток")]'
    black_check_box = './/label[text()="чёрный жемчуг"]'
    grey_check_box = './/label[text()="серая безысходность"]'
    comment_field = './/input[@placeholder="Комментарий для курьера"]'
    order_on_body_btn = './/div[@class = "Order_Buttons__1xGrp"]//button[text()="Заказать"]'
    order_header_btn = './/div[@class = "Header_Nav__AGCXC"]//button[text() = "Заказать"]'
    want_to_finish_title = './/div[text()="Хотите оформить заказ?"]'
    yes_btn = './/button[text()="Да"]'
    order_processed_title = './/div[text()="Заказ оформлен"]'
